server:
  host: 0.0.0.0
  port: 9091

jwt_secret: "secretjwt"

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: ["grafana.localhost", "gitea.localhost"]
      policy: one_factor

session:
  name: authelia_session
  expiration: 3600
  inactivity: 300
  domain: localhost
  secret: "yoursecretvalue"

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
